let quoteImagination = [
    "Don't part with your illusions.<br>When they are gone, you may still exist, but you have ceased to live.<br><br>- Mark Twain",
    "Everything you can imagine is real.<br><br>- Pablo Picasso",
    "Imagination is the beginning of creation.<br>You imagine what you desire,<br>you will what you imagine,<br>you create what you will.<br><br>- George Bernard Shaw",
    "Imagination is the discovering faculty, pre-eminently.<br>It is that which penetrates into the unseen worlds around us.<br><br>- Ada Lovelace",
    "They did not know what was impossible, so they did it.<br><br>- Mark Twain",
    "Thinking is the enemy of creativity.<br>It's self-conscious, and anything self-conscious is lousy.<br>You can't try to do things. You simply must do things.<br><br>- Ray Bradbury",
    "To those devoid of imagination a blank place on the map is a useless waste;<br>to others, the most valuable part.<br><br>- Aldo Leopold",
    "You can't depend on your eyes when your imagination is out of focus<br><br>- Mark Twain",
];

let quotePhilosophy = [
    "Ah, but a man's reach should exceed his grasp, or what's a heaven for?<br><br>- Robert Browning",
    "Any experience that touches you, in any particular way, is good.<br>It can be a horrible experience.<br><br>- Ray Bradbury",
    "Anything forced is not beautiful.<br><br>- Xenophon",
    "Even when I was in a crowd, I was always alone.<br><br>- Ernest Hemingway",
    "If I have seen further it is by standing on the shoulders of giants.<br><br>- Isaac Newton",
    "In the midst of winter, I found there was, within me, an invincible summer.<br><br>- Albert Camus",
    "Knowledge is just opinion that you trust enough to act upon.<br><br>- Orson Scott Card",
    "Learn what is to be taken seriously and laugh at the rest.<br><br>- Herman Hesse",
    "Life is the art of drawing without an eraser.<br><br>- John W. Gardner",
    "Mathematical science...is the language of unseen relations between things.<br>But to use and apply that language, we must be able to fully appreciate,<br>to feel, to seize the unseen.<br><br>- Ada Lovelace",
    "Nonconformity is the highest evolutionary attainment of social animals.<br><br>- Aldo Leopold",
    "No human being will ever know the truth,<br>for even if they happened to say it by chance,<br>they would not know they had done so.<br><br>- Xenophon",
    "Perhaps it would be better for science,<br>that all criticism should be avowed.<br><br>- Charles Babbage",
    "Self-confidence should always ride side by side<br>with a strong sense of humility.<br><br>- Xenophon",
    "Solitude is fine, but you need someone to tell that solitude is fine.<br><br>- Honoré de Balzac",
    "Some of us think holding on makes us strong but sometimes it is letting go.<br><br>- Herman Hesse",
    "Sometimes it is the people who no one imagines anything of<br>who do the things that no one can imagine.<br><br>- Alan Turing",
    "Specialization is for insects.<br><br>- Robert A. Heinlein",
    "The only true wisdom is in knowing you know nothing.<br><br>- Socrates",
    "There is no fixed physical reality, no single perception,<br>just numerous ways of interpreting world views.<br><br>- Deepak Chopra",
    "The true sign of intelligence is not knowledge, but imagination.<br><br>- Albert Einstein",
    "The worst enemy...is self-doubt.<br><br>- Sylvia Plath",
    "There are some who can live without wild things and some who cannot.<br><br>- Aldo Leopold",
    "There is only one good, knowledge, and one evil, ignorance.<br><br>- Socrates",
    "Who is to decide which is the grimmer sight:<br>withered hearts or empty skulls?<br><br>- Honoré de Balzac",
    "You can cut all the flowers, but you cannot keep spring from coming.<br><br>- Pablo Neruda",
    "You can't wait for inspiration, you have to go after it with a club.<br><br>- Jack London",
];

let quoteStars = [
    "Dwell on the beauty of life.<br>Watch the stars, and see yourself running with them.<br><br>- Marcus Aurelius",
    "I have ceased to question stars and books;<br>I have begun to listen to the teaching my blood whispers to me.<br><br>- Herman Hesse",
    "I love the stars. Because they can't say anything.<br>Because they do not judge anyone.<br><br>- Natsuki Takaya",
    "It had been my wish and with the years I had attained solitude.<br>It was cold...but also still, wonderfully still<br>and vast like the space in which the stars revolve.<br><br>- Herman Hesse",
    "Moonlight drowns out all but the brightest stars.<br><br>- J.R.R. Tolkien",
    "Stars and galaxies are transient, fleeting things that twinkle like fireflies<br>and then vanish into cold and dust.<br><br>- Neil Gaiman",
    "Stars, too, were time travelers.<br>How many of those ancient points of light<br>were the last echoes of suns now dead...<br>their light not yet come this far?<br><br>- Ransom Riggs",
    "The cosmos is within us.<br><br>- Carl Sagan",
    "The fault...lies not in our stars, but in ourselves.<br><br>- William Shakespeare",
    "The stars are like the trees in the forest, alive and breathing.<br>And they're watching me.<br><br>- Haruki Murakami",
    "There is no easy way from the earth to the stars.<br><br>- Seneca",
    "We have calcium in our bones, iron in our veins,<br>carbon in our souls, and nitrogen in our brains.<br>Ninety-three percent stardust, with souls made of flames.<br><br>- Nikita Gill",
    "When it is dark enough, you can see the stars.<br><br>- Ralph Waldo Emerson",
    ];

let quoteSystems = [
    "A bad system will beat a good person every time.<br><br>- W. Edwards Deming",
    "A good system shortens the road to the goal.<br><br>- Orison Swett Marden",
    "I must create a system or be enslaved by another man's;<br>I will not reason and compare:<br>my business is to create.<br><br>- William Blake",
    "The mind and body are not separate units but one integrated system.<br><br>-  Bernie Siegel",
    "There are lies, damned lies, and statistics.<br><br>- Mark Twain",
    "There must be forethought, system, planning, intelligence,<br>and honest purpose. Seeming to do is not doing.<br><br>- Thomas A. Edison",
];

let quoteVocation = [
    "An unfulfilled vocation drains the color from existence.<br><br>- Honoré de Balzac",
    "An intellectual is someone whose mind watches itself.<br>I like this, because I am happy to be both the watcher and the watched.<br><br>- Albert Camus",
    "Every morning I jump out of bed and step on a landmine.<br>The landmine is me. After the explosion,<br>I spent the rest of the day putting the pieces back together.<br><br>- Ray Bradbury",
    "If you want to be good, you have to practice, practice, practice.<br>If you don't love what you're doing, then don't do it.<br><br>- Ray Bradbury",
    "I may not have been sure about what really did interest me,<br>but I was absolutely sure about what didn't.<br><br>- Albert Camus",
    "It's lack that gives us inspiration. It's not fullness.<br><br>- Ray Bradbury",
    "Misleaders are slow to work hard but quick to act on greed.<br>They convince their men that dishonest behavior leads to great wealth.<br><br>- Xenophon",
    "Problems cannot be solved at the same level of awareness that created them.<br><br>- Albert Einstein",
    "The more I study, the more insatiable do I feel my genius for it to be.<br><br>- Ada Lovelace",
    "The precise role of the artist, then, is to illuminate that darkness,<br>blaze roads through that vast forest,<br>so that we will not lose sight of its purpose.<br><br>- James Baldwin",
    "There are basically two types. People who accomplish things, and people who claim to have accomplished things. The first group is less crowded.<br><br>- Mark Twain",
    "There is no such thing as a great talent without great willpower.<br><br>- Honoré de Balzac",
    "What a horse does under compulsion he does blindly,<br>and his performance is no more beautiful<br>than a ballet dancer taught by whip and goad.<br><br>- Xenophon",
];

let quoteWriting = [
    "Although only breath, words which I command are immortal.<br><br>- Sappho",
    "Any fool can write code that a computer can understand.<br>Good programmers write code that humans can understand.<br><br>- Martin Fowler",
    "Code is like humor.<br>When you have to explain, it's bad.<br><br>- Cory House",
    "If you can't give me poetry, can't you give me poetical science?<br><br>- Ada Lovelace",
    "If you know how to read, you have a complete education about life.<br><br>- Ray Bradbury",
    "It is far, far easier to make a correct program fast<br>than it is to make a fast program correct.<br></br>- Herb Sutter",
    "It is not possible to produce a set of rules purporting to describe<br>what a man should do in every conceivable set of circumstances.<br><br>- Alan Turing",
    "May I write words more naked than flesh,<br>stronger than bone, more resilient than sinew.<br><br>- Sappho",
    "The difference between the almost right word and the right word is really a large matter - 'tis the difference between the lightning-bug and the lightning.<br><br>- Mark Twain",
    "The first draft of anything is shit.<br><br>- Ernest Hemingway",
    "There is nothing to writing.<br>All you do is sit down at a typewriter and bleed.<br><br>- Ernest Hemingway",
    "You think you know when you can learn,<br>are more sure when you can write,<br>even more when you can teach,<br>but certain when you can program.<br><br>- Alan Perlis",
];