let dataPortfolioWebpage = [
    {filename:"contact", extension:"html", features:["menu hyperlinks", "contact content",], linesofcode:83,},
    {filename:"contact", extension:"js", features:["dynamic form", "error validation",], linesofcode:65,},
    {filename:"designdoc", extension:"md", features:["documentation", "menu hyperlinks",], linesofcode:258,},
    {filename:"faq", extension:"html", features:["menu hyperlinks", "faq content",], linesofcode:125,},
    {filename:"imageloader", extension:"js", features:["preloaded images",], linesofcode:16,},
    {filename:"index", extension:"html", features:["homepage content", "menu hyperlinks",], linesofcode:53,},
    {filename:"projects", extension:"html", features:["menu hyperlinks", "projects content",], linesofcode:132,},
    {filename:"projects", extension:"js", features:["random quotes", "responsive layout",], linesofcode:176,},
    {filename:"quotedata", extension:"js", features:["random quotes", "quotes content"], linesofcode:96,},
    {filename:"quotegenerator", extension:"js", features:["random quotes",], linesofcode:5,},
    {filename:"readme", extension:"md", features:["documentation", "menu hyperlinks", ], linesofcode:64,},
    {filename:"style", extension:"css", features:["responsive layout", "static layout",], linesofcode:0,},
    {filename:"table", extension:"css", features:["static layout",], linesofcode:0,},
    {filename:"tabledata", extension:"js", features:["table content",], linesofcode:14,},
    {filename:"tablegenerator", extension:"js", features:["dynamic tables", "responsive layout",], linesofcode:0,},
]