let dataPortfolioWebpage = [
    {filename:"contact", extension:"html", features:["contact page", "dynamic content","error validation","image preloading","input fields","static content",], linesofcode:83, variables:0, functions:0, classes:3,},
    {filename:"contact", extension:"js", features:["error validation","functionality","regex"], linesofcode:65, variables:22, functions:2, classes:0,},
    {filename:"designdoc", extension:"html", features:["documentation",], linesofcode:258, variables:0, functions:0, classes:0,},
    {filename:"faq", extension:"html", features:["faq page", "image preloading","static content",], linesofcode:125, variables:0, functions:0, classes:7,},
    {filename:"imageloader", extension:"js", features:["functionality","image preloading","storage",], linesofcode:16, variables:1, functions:1, classes:0,},
    {filename:"index", extension:"html", features:["home page","image preloading","random quotes","dynamic content","static content",], linesofcode:53, variables:0, functions:0, classes:6,},
    {filename:"mermaid", extension:"css", features:["custom theme","static layout","styling",], linesofcode:26, variables:0, functions:0, classes:12,},
    {filename:"mermaidflowchart", extension:"html", features:["hyperlinked mermaid charts"], linesofcode:92, variables:0, functions:2, classes:1,},
    {filename:"mermaidganttchart", extension:"html", features:["hyperlinked mermaid charts"], linesofcode:95, variables:0, functions:2, classes:1,},
    {filename:"mermaidpiechart", extension:"html", features:["hyperlinked mermaid charts"], linesofcode:35, variables:0, functions:2, classes:1,},
    {filename:"projects", extension:"html", features:["dynamic content","image preloading","projects showcase page","static content",], linesofcode:132, variables:0, functions:0, classes:8,},
    {filename:"projects", extension:"js", features:["functionality","projects showcase",], linesofcode:176, variables:48, functions:2, classes:0,},
    {filename:"quotedata", extension:"js", features:["random quote generation","storage",], linesofcode:96, variables:6, functions:0, classes:0,},
    {filename:"quotegenerator", extension:"js", features:["functionality","random quote generation",], linesofcode:5, variables:2, functions:0, classes:0,},
    {filename:"readme", extension:"html", features:["documentation","static content",], linesofcode:159, variables:0, functions:0, classes:0,},
    {filename:"style", extension:"css", features:["custom theme","responsive layout","styling",], linesofcode:265, variables:0, functions:0, classes:40,},
    {filename:"table", extension:"css", features:["custom theme","static layout","styling",], linesofcode:23, variables:0, functions:0, classes:0,},
    {filename:"table", extension:"html", features:["data-driven content","table generation",], linesofcode:32, variables:0, functions:0, classes:0,},
    {filename:"tabledata", extension:"js", features:["storage","table generation",], linesofcode:21, variables:0, functions:0, classes:1,},
    {filename:"tablegenerator", extension:"js", features:["functionality","table generation",], linesofcode:19, variables:0, functions:1, classes:0,},
]