let dataPortfolioWebpage = [
    {filename:"contact", extension:"html", features:["contact page", "dynamic content","error validation","image preloading","input fields","static content",], module:"Portfolio Website", linesofcode:83,},
    {filename:"contact", extension:"js", features:["error validation","functionality","regex"], module:"Portfolio Website", linesofcode:65,},
    {filename:"designdoc", extension:"html", features:["documentation",], module:"Project Data", linesofcode:258,},
    {filename:"faq", extension:"html", features:["faq page", "image preloading","static content",], module:"Portfolio Website", linesofcode:125,},
    {filename:"imageloader", extension:"js", features:["functionality","image preloading","storage",], module:"Portfolio Website", linesofcode:16,},
    {filename:"index", extension:"html", features:["home page","image preloading","random quotes","dynamic content","static content",], module:"Portfolio Website", linesofcode:53,},
    {filename:"mermaid", extension:"css", features:["custom theme","static layout","styling",], module:"Project Data", linesofcode:26,},
    {filename:"mermaidflowchart", extension:"html", features:["hyperlinked mermaid charts"], module:"Project Data", linesofcode:92,},
    {filename:"mermaidganttchart", extension:"html", features:["hyperlinked mermaid charts"], module:"Project Data", linesofcode:95,},
    {filename:"mermaidpiechart", extension:"html", features:["hyperlinked mermaid charts"], module:"Project Data", linesofcode:35,},
    {filename:"projects", extension:"html", features:["dynamic content","image preloading","projects showcase page","static content",], module:"Portfolio Website", linesofcode:132,},
    {filename:"projects", extension:"js", features:["functionality","projects showcase",], module:"Portfolio Website", linesofcode:176,},
    {filename:"quotedata", extension:"js", features:["random quote generation","storage",], module:"Quote Generator", linesofcode:96,},
    {filename:"quotegenerator", extension:"js", features:["functionality","random quote generation",], module:"Quote Generator", linesofcode:5,},
    {filename:"readme", extension:"html", features:["documentation","static content",],  module:"Project Data", linesofcode:159,},
    {filename:"readme", extension:"md", features:["documentation","github",],  module:"GitHub", linesofcode:131,},
    {filename:"style", extension:"css", features:["custom theme","responsive layout","styling",],  module:"Portfolio Website", linesofcode:265,},
    {filename:"table", extension:"css", features:["custom theme","static layout","styling",],  module:"Table Generator", linesofcode:23,},
    {filename:"table", extension:"html", features:["data-driven content","table generation",],  module:"Project Data", linesofcode:32,},
    {filename:"tabledata", extension:"js", features:["storage","table generation",],  module:"Table Generator", linesofcode:21,},
    {filename:"tablegenerator", extension:"js", features:["functionality","table generation",],  module:"Table Generator", linesofcode:19,},
]